language: node_js

node_js:
    - "node"
    - "12"
    - "10"
    # - "8"
    # - "6"
    #- "4"
    #- "0.12"
    #- "0.11"
    #- "0.10"



sudo: false



git:
    submodules: false



before_script:
    - make install



script:
    - make test



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/7dd5cda20cc3c4a9dcb0

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
